// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gqejbdhbedmkesjnwdnw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdxZWpiZGhiZWRta2Vzam53ZG53Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMTkyMTEsImV4cCI6MjA2Mzc5NTIxMX0.G34z13AfSBkW6M6PJ-KG4AZqbq3w1cTYVoPfTnIpOvs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);